name: Johnny Summers Racing
favicon: null
layout_spectrum: 0.34303105459548533
typography_spectrum: 0.216276241466403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8661098186857998
  lightness: 0.3809935669414699
  saturation: 0.9154433864168823
  rhythmicContrast: 0.8644346497021616
purpose: []
